# Generated by Django 4.2.4 on 2023-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='ecom.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default='media/place_holder_book.png', null=True, upload_to=''),
        ),
    ]
